services:
  - type: web
    name: crewai-test
    env: python
    pythonVersion: "3.11"
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    repo: https://github.com/themikehage/crewai-test
    branch: master
    autoDeploy: true